CREATE TABLE TRUCK_DRIVER (
	DOCUMENT_ID VARCHAR(11) NOT NULL PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	LICENCE_PLATE VARCHAR(7) NOT NULL,
	PHONE VARCHAR(11) NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

-- INSERT INTO TRUCK_DRIVER (DOCUMENT_ID, NAME, EMAIL, LICENCE_PLATE, PHONE) VALUES ('06639701480', 'José Augusto', 'jaugustocesar@gmail.com', 'PFC9585', '87996396921');