CREATE TABLE TRUCK_DRIVER (
	ID INTEGER(255) AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
	DOCUMENT_ID VARCHAR(11) NOT NULL UNIQUE,
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
	LICENCE_PLATE VARCHAR(7) NOT NULL UNIQUE,
	PHONE VARCHAR(11) NOT NULL UNIQUE,
	MODIFIED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO TRUCK_DRIVER (NAME, DOCUMENT_ID, EMAIL, LICENCE_PLATE, PHONE) VALUES ('José Augusto', '06639701480', 'jaugustocesar@gmail.com', 'PFC9585', '87996396921');